export const IPC_CHANNELS = {
  helloGetMessage: 'hello:get-message',
  fileCreateDB: 'file:create-db',
  fileListDB: 'file:list-db',
  fileDeleteDB: 'file:delete-db',
  fileGetSelectedDB: 'file:get-selected-db',
  fileSetSelectedDB: 'file:set-selected-db',
  fileClearSelectedDB: 'file:clear-selected-db',
  dbSync: 'db:sync',
  dbReconnect: 'db:reconnect',
  userCreate: 'user:create',
  userGetAll: 'user:get-all',
  userGetById: 'user:get-by-id',
  userUpdate: 'user:update',
  userDelete: 'user:delete',
  userAuth: 'user:auth',
  //ANNEE SCOLAIRE
  anneeScolaireCreate: 'anneeScolaire:create',
  anneeScolaireGetAll: 'anneeScolaire:get-all',
  anneeScolaireGetById: 'anneeScolaire:get-by-id',
  anneeScolaireUpdate: 'anneeScolaire:update',
  anneeScolaireDelete: 'anneeScolaire:delete',
  //ELEVE
  eleveCreate: 'eleve:create',
  eleveGetAll: 'eleve:get-all',
  eleveGetById: 'eleve:get-by-id',
  eleveUpdate: 'eleve:update',
  eleveDelete: 'eleve:delete',
  //CLASSE
  classeCreate: 'classe:create',
  classeGetAll: 'classe:get-all',
  classeGetById: 'classe:get-by-id',
  classeUpdate: 'classe:update',
  classeDelete: 'classe:delete',
  //INSCRIPTION
  inscriptionCreate: 'inscription:create',
  inscriptionGetAllThisYear: 'inscription:get-all-this-year',
  inscriptionGetAll: 'inscription:get-all',
  inscriptionGetById: 'inscription:get-by-id',
  inscriptionUpdate: 'inscription:update',
  inscriptionDelete: 'inscription:delete',
  //TYPEFRAIS
  typeFraisCreate: 'typeFrais:create',
  typeFraisGetAll: 'typeFrais:get-all',
  typeFraisGetById: 'typeFrais:get-by-id',
  typeFraisUpdate: 'typeFrais:update',
  typeFraisDelete: 'typeFrais:delete',
  //TARIF
  tarifCreate: 'tarif:create',
  tarifGetAll: 'tarif:get-all',
  tarifGetById: 'tarif:get-by-id',
  tarifUpdate: 'tarif:update',
  tarifDelete: 'tarif:delete',
  //PAIEMENT
  paiementCreate: 'paiement:create',
  paiementGetAll: 'paiement:get-all',
  paiementGetById: 'paiement:get-by-id',
  paiementUpdate: 'paiement:update',
  paiementDelete: 'paiement:delete',
  databaseStatus: 'database:status',
  //KPI
  statsKpiGlobal:               'stats:kpi-global',
  statsEffectifsClasse:         'stats:effectifs-classe',
  statsPaiementParClasse:       'stats:paiement-par-classe',
  statsPaiementParTypeFrais:    'stats:paiement-par-type-frais',
  statsElevesEnRetard:          'stats:eleves-en-retard',
  statsEncaissementMensuel:     'stats:encaissement-mensuel',
  statsDetailPaiementsEleve:    'stats:detail-paiements-eleve',
  statsTopClassesRecouvrement:  'stats:top-classes-recouvrement',
} as const
