export const IPC_CHANNELS = {
  helloGetMessage: 'hello:get-message',
  fileCreateDB: 'file:create-db',
  fileListDB: 'file:list-db',
  fileDeleteDB: 'file:delete-db',
  fileGetSelectedDB: 'file:get-selected-db',
  fileSetSelectedDB: 'file:set-selected-db',
  fileClearSelectedDB: 'file:clear-selected-db',
  dbSync: 'db:sync',
  dbReconnect: 'db:reconnect',
  userCreate: 'user:create',
  userGetAll: 'user:get-all',
  userGetById: 'user:get-by-id',
  userUpdate: 'user:update',
  userDelete: 'user:delete',
  userAuth: 'user:auth',
  //ANNEE SCOLAIRE
  anneeScolaireCreate: 'anneeScolaire:create',
  anneeScolaireGetAll: 'anneeScolaire:get-all',
  anneeScolaireGetById: 'anneeScolaire:get-by-id',
  anneeScolaireUpdate: 'anneeScolaire:update',
  anneeScolaireDelete: 'anneeScolaire:delete',
  //ELEVE
  eleveCreate: 'eleve:create',
  eleveGetAll: 'eleve:get-all',
  eleveGetById: 'eleve:get-by-id',
  eleveUpdate: 'eleve:update',
  eleveDelete: 'eleve:delete',
  databaseStatus: 'database:status',
} as const
