export const IPC_CHANNELS = {
  helloGetMessage: 'hello:get-message',
  fileCreateDB: 'file:create-db',
  fileListDB: 'file:list-db',
  fileDeleteDB: 'file:delete-db',
  fileGetSelectedDB: 'file:get-selected-db',
  fileSetSelectedDB: 'file:set-selected-db',
  fileClearSelectedDB: 'file:clear-selected-db',
  dbSync: 'db:sync',
  dbReconnect: 'db:reconnect',
  userCreate: 'user:create',
  userGetAll: 'user:get-all',
  userGetById: 'user:get-by-id',
  userUpdate: 'user:update',
  userDelete: 'user:delete',
  userAuth: 'user:auth',
  databaseStatus: 'database:status',
} as const
